name = "Reminiscent Create"
author = "Amronos"
version = "4.0.3"
description = "[1.20.1] A modpack that hopes to provide an epic Create experience with all your favorite Create add-ons, Magic Mods, and many vanilla+ mods, while also keeping optimization in mind."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a73008d7289636d5e7c0723ea610bd78d5e82e0d17430505780c349af125fd6"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
